---
- name: add authorized keys
  authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  with_file:
    - roles/meine-neue-rolle/files/public_keys/paul.pub
  when: ansible_distribution in ['Ubuntu', 'Debian']
  tags:
  - ssh_keys

- name: add several users to the system
  user:
    name: "{{ item.name }}"
    comment: "{{ item.fullname }}"
    state: present
    shell: /bin/bash
  with_items:
      - { name: paul, fullname: "Paul Loewen" }

- name: Set authorized keys for each user
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', 'roles/meine-neue-rolle/files/public_keys/{{ item.name }}.pub') }}"
  with_items:
      - {name: paul }

- name: Add "{{ item.name }}" user to sudoers
  lineinfile:
    path: /etc/sudoers.d/{{ item.name }}
    line: '{{ item.name }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  with_items:
      - {name: paul }
